### ISSUE TITLE
After I Submit my "Prove" Transaction - UI Shows "Invalid Tx Hash"

### ISSUE THREAD

**Issue by MSilb7** [ethereum-optimism/superchain-relayer#11]
**Describe the bug**

**To Reproduce**
1. Enter L2 Tx hash
2. Submit Prover Transaction (go through MM popups)
3. Refresh Page
4. Search Tx
5. See "Invalid Tx Hash" Error

**Expected behavior**
I se feedback showing me the status of my proving tx

**Comment by zainbacchus** [comment]
Thanks for this! Def a known issue, https://github.com/ethereum-optimism/superchain-relayer/issues/4 

We'll get this added once we add polish to this tool!

**Comment by zainbacchus** [comment]
Addressed in #18
