### ISSUE TITLE
Relayer Can't Find Multi-Withdrawal Transactions

### ISSUE THREAD

**Issue by MSilb7** [ethereum-optimism/superchain-relayer#12]
**Describe the bug**
When I search for a transaction with multiple withdrawals, I get a "Invalid transaction hash" error. 

**To Reproduce**
1. Search for this transaction: 0x9592c59d4ef1a7100ae833c7a7721e379b8544b629d827d3ea6f680bc72eaee2
https://optimistic.etherscan.io/tx/0x9592c59d4ef1a7100ae833c7a7721e379b8544b629d827d3ea6f680bc72eaee2

**Expected behavior**
I'm able to relay and withdraw

**Screenshots**
<img width="348" alt="image" src="https://github.com/ethereum-optimism/superchain-relayer/assets/4006780/9a103bf5-3127-4104-9670-a64fda65c8a8">

**Comment by zainbacchus** [comment]
Relevant PR that needs to be merged then we can bump the SDK version: https://github.com/ethereum-optimism/optimism/pull/6053

**Comment by roninjin10** [comment]
To support this in ui an input for withdrawal index would have to exists that let's you pick the withdrawal index.  Since it's odd ux we could make it only show up with it detects more than 1 withdrawal

**Comment by MSilb7** [comment]
> To support this in ui an input for withdrawal index would have to exists that let's you pick the withdrawal index. Since it's odd ux we could make it only show up with it detects more than 1 withdrawal

Hi, wondering if this is planned & if so do we have an ETA?

**Comment by cryptoharry** [comment]
> Relevant PR that needs to be merged then we can bump the SDK version: [ethereum-optimism/optimism#6053](https://github.com/ethereum-optimism/optimism/pull/6053)

Looks like it has been merged successfully. Any ETA for when update will be reflected on UI?

**Comment by zainbacchus** [comment]
Needs https://github.com/ethereum-optimism/optimism/pull/6254 to be merged / released as well

**Comment by zainbacchus** [comment]
Thanks for your patience! Addressed in https://github.com/ethereum-optimism/superchain-relayer/pull/18
