### ISSUE TITLE
Relayer Does not bring up Wallet when Proving a Transaction

### ISSUE THREAD

**Issue by cryptoharry** [ethereum-optimism/superchain-relayer#15]
**Describe the bug**
When pressing "execute" to prove a transaction, nothing happens with my connected wallet (metamask).

**To Reproduce**
1. Search for the following transaction: 0x9fadd500066868c8290719083b0c2aad91ab4c41110bf822ac36d374bda256c9
https://optimistic.etherscan.io/tx/0x9fadd500066868c8290719083b0c2aad91ab4c41110bf822ac36d374bda256c9
2. Click on "Execute" on the UI

**Expected behavior**
A transaction will pop up, with a proof to start the 7 day withdrawal period.

**Screenshots**
![image](https://github.com/ethereum-optimism/superchain-relayer/assets/110295612/2da57a26-7f27-4c99-a15e-777d3280be8e)

**Comment by brian0641** [comment]
I had the same issue when trying to "Execute" on a "Message is ready to be proved" state. 

The error message in the console log was:
rkle-utils.ts:67 Uncaught (in promise) TypeError: provider.send is not a function
    at makeStateTrieProof (merkle-utils.ts:67:32)
    at CrossChainMessenger.getBedrockMessageProof (cross-chain-messenger.ts:1376:34)
    at async Object.proveMessage (cross-chain-messenger.ts:1778:21)
    at async CrossChainMessenger.proveMessage (cross-chain-messenger.ts:1474:16)
    at async executeMessage (Relayer.tsx:91:9)

**Comment by zainbacchus** [comment]
> I had the same issue when trying to "Execute" on a "Message is ready to be proved" state.
> 
> The error message in the console log was: rkle-utils.ts:67 Uncaught (in promise) TypeError: provider.send is not a function at makeStateTrieProof (merkle-utils.ts:67:32) at CrossChainMessenger.getBedrockMessageProof (cross-chain-messenger.ts:1376:34) at async Object.proveMessage (cross-chain-messenger.ts:1778:21) at async CrossChainMessenger.proveMessage (cross-chain-messenger.ts:1474:16) at async executeMessage (Relayer.tsx:91:9)

Hey this was addressed in #17! 

@cryptoharry are you still seeing this issue?

**Comment by cryptoharry** [comment]
@zainbacchus I can confirm this is now resolved, and I have submitted the proof on-chain.

Thanks a lot for the help
