### ISSUE TITLE
[bug (hard blocker)] Can Not Execute Multi-Withdrawal Transactions

### ISSUE THREAD

**Issue by MSilb7** [ethereum-optimism/superchain-relayer#25]
Re-opening/referencing https://github.com/ethereum-optimism/superchain-relayer/issues/12 + https://github.com/ethereum-optimism/superchain-relayer/pull/18

I am able to prove multi-withdrawal transactions, but when I go to execute > 7 days later, the `invalid transaction hash` error returns.
![image](https://github.com/ethereum-optimism/superchain-relayer/assets/4006780/0e9b25ab-c702-48eb-a4cc-5a6bf744b3d4)

**Comment by tarunkhasnavis** [comment]
Confirming relay of three blocked withdrawals

- `0x1fe136e3acbb9a0e23c654bc6eeea44d2bab1007808ae4da20e00568bd73a7dc`
- `0x80aa9b96ae8170883ca2d84499662955933e8acc56e699f68070fd4b0fb71fb2`
- `0x9592c59d4ef1a7100ae833c7a7721e379b8544b629d827d3ea6f680bc72eaee2`

Wallet for initiation: https://optimistic.etherscan.io/address/0xb2644085922Cd777b7F31698A4A7c4E83Cd1A8a8
Wallet used to relay: https://etherscan.io/address/0xC009EC1DE31478d24f01Df3F41E437AAb96445b6

**Comment by tarunkhasnavis** [comment]
CRR: https://github.com/ethereum-optimism/superchain-relayer/pull/26
