### ISSUE TITLE
Add a note that your selected network must be Ethereum L1

### ISSUE THREAD

**Issue by sbvegan** [ethereum-optimism/superchain-relayer#28]
**Is your feature request related to a problem? Please describe.**

The web app doesn't work unless your wallet is connected to Ethereum.

**Describe the solution you'd like**

I think a note on the front page should be sufficient. It could also show an invalid network selection error when users are not connected to Ethereum.

**Describe alternatives you've considered**

n/a

**Additional context**

n/a

**Comment by zainbacchus** [comment]
this was fixed by @jakim929 (thank you!)
