### ISSUE TITLE
Can we rename to `op-stack-relayer`

### ISSUE THREAD

**Issue by pegahcarter** [ethereum-optimism/superchain-relayer#33]
**Is your feature request related to a problem? Please describe.**
There are OP-stack chains building which have identical or nearly identical setups.  They would benefit from this sdk.

**Describe the solution you'd like**
I propose we rename this repo to `op-stack-relayer` to indicate this sdk is available for more than just superchains.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by zainbacchus** [comment]
Hi @pegahcarter thanks for your suggestion - while many chains are built on the OP Stack, we can't ensure that this tool will support them. This tool is intended for chains part of the Superchain that are using the standard configuration and will be supported by first party tools. 

You can read more about the standard configuration here: https://gov.optimism.io/t/season-6-draft-standard-rollup-charter/8135
