### ISSUE TITLE
Add support for Base 

### ISSUE THREAD

**Issue by zainbacchus** [ethereum-optimism/superchain-relayer#5]
ChainID is hard coded right now

**Comment by zainbacchus** [comment]
Add Goerli

**Comment by zainbacchus** [comment]
Added Base Goerli in https://github.com/zainbacchus/simple-relayer/commit/5b3829ed1af5525179f4bd1968f0779564d41e72

**Comment by huihzhao** [comment]
any plan to open source the optimism sdk?

**Comment by zainbacchus** [comment]
> any plan to open source the optimism sdk?

Hey there! What do you mean? SDK is already open source. https://github.com/ethereum-optimism/optimism/tree/develop/packages/sdk

**Comment by zainbacchus** [comment]
Reference for Base Mainnet: https://github.com/wagmi-dev/references/pull/426/files

**Comment by zainbacchus** [comment]
h/t @jakim929 ty!
