### ISSUE TITLE
Stuck on "Withdrawal Status"

### ISSUE THREAD

**Issue by MSilb7** [ethereum-optimism/superchain-relayer#54]
**Bug 1 - Post FP Withdrawals**
**Bug Description**
Enter a transaction hash for OP Mainnet, press search, and the message gets stuck on `Loading withdrawal status...` with no option to prove or relay.

**Steps to Reproduce**

See above. OPM Transaction: `0x2a523f1b74b93f5d8c1bdc7e5a1d106e7b2c6b1e31c3449a370b05048fec5ada`

![image](https://github.com/user-attachments/assets/1737017b-84a2-4621-a4c5-8379a8efd3ed)

**Bug 2 - Pre FP Withdrawals**
OPM Transaction: `0xd45b140c2240ec54153cce72e2176cd0d263a9fbf81620b09dcc9a19faa92c15`

This tx needs to be re-proven, but is still stuck on `Loading withdrawal status...`

**Comment by MSilb7** [comment]
Update on #1 - I now see "Ready to Prove" but "Prove" is grayed out
![image](https://github.com/user-attachments/assets/0a79f85d-084c-4a9c-9e49-74bd3814806c)

**Comment by nitaliano** [comment]
@MSilb7 I'm seeing the button enabled for https://github.com/ethereum-optimism/superchain-relayer/issues/54#issuecomment-2359597390

<img width="671" alt="Screenshot 2024-09-19 at 10 47 00 AM" src="https://github.com/user-attachments/assets/babe0ed8-c3f3-4a12-b818-dde0b29d1ac9">

**Comment by MSilb7** [comment]
Hi, yeah I'm able to prove the new transaction as well, so may have been a timing thign before @nitaliano

**Comment by nitaliano** [comment]
The pre fp hash is showing `ready-to-prove`
<img width="724" alt="Screenshot 2024-09-23 at 1 06 07 PM" src="https://github.com/user-attachments/assets/34b634c7-ea37-4cf6-90f0-332de0826368">

**Comment by MSilb7** [comment]
Nice, just started proving old ones! We are in business.
